Algoritmo "círculo"

// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/03/2026
Var
   r, area, con:real

Inicio

       escreva("Mostre o valor do Raio do Círculo: ")
       leia(r)

       con <- Pi
       area <- ( con* r^2 )

       
       escreva("A área do círculo é: ",area:1:3)

Fimalgoritmo